- stop talking about yoself
- (related) you are what you are doing right now
- you can either love things or loathe things--loathe things
- time > money, always
- less > more, always
- fish in the summer, meat in the winter
- pull before you push (works for git too)
- take lots of notes, they are probably more important that what is note
- living on the top floor is a chance for a daily workout
