- stop talking about yourself
- (related) you are what you are doing right now
- you can either love things or loathe things--loathe things
- time always > money
- less always > more
- fish in the summer, meat in the winter
